stage('build') {
    node('util') {
        git([url: env.REPO_URL, branch: env.BRANCH])
        withCredentials([$class: "AmazonWebServiceCredentialsBinding",
            credentialsId: "packer",
            accessKeyVariable: "AWS_ACCESS_KEY_ID",
            secretKeyVariable: "AWS_SECRET_ACCESS_KEY"]) {
            sh("make box-docker_slave-ubuntu-bionic-x86_64-aws")
        }
    }
}
