stage("build & upload") {
    parallel windows: {
        node("windows") {
            sh("rm -rf **")
            git([url: env.REPO_URL, branch: env.BRANCH])
            sh("make test")
            sh("tar -C target -zcvf safe_cli-master-windows-cache.tar.gz .")
            withAWS(credentials: "aws_jenkins_build_artifacts_user", region: "eu-west-2") {
                s3Delete(
                    bucket: "${env.S3_BUCKET}",
                    path: "safe_cli-master-windows-cache.tar.gz")
                s3Upload(
                    bucket: "${env.S3_BUCKET}",
                    file: "safe_cli-master-windows-cache.tar.gz",
                    acl: "PublicRead")
            }
        }
    },
    macos: {
        node("osx") {
            sh("rm -rf **")
            git([url: env.REPO_URL, branch: env.BRANCH])
            sh("make test")
            sh("tar -C target -zcvf safe_cli-master-macos-cache.tar.gz .")
            withAWS(credentials: "aws_jenkins_build_artifacts_user", region: "eu-west-2") {
                s3Delete(
                    bucket: "${env.S3_BUCKET}",
                    path: "safe_cli-master-macos-cache.tar.gz")
                s3Upload(
                    bucket: "${env.S3_BUCKET}",
                    file: "safe_cli-master-macos-cache.tar.gz",
                    acl: "PublicRead")
            }
        }
    }
}
