stage("build & push") {
    commit_hash = ""
    node("util") {
        git([url: env.REPO_URL, branch: env.BRANCH])
        sh("make build-container")
        sh("make push-container")
        commitHash = sh(
            returnStdout: true,
            script: "git rev-parse --short HEAD").trim()
    }
    build(
        job: "ami_build-safe_vault_slave",
        parameters:
        [
            [
                $class: "StringParameterValue",
                name: "SAFE_COMMIT_HASH",
                value: commitHash
            ]
        ],
        wait: false)
}
