stage("build & push") {
    commit_hash = ""
    parallel non_mock_container: {
        node("util") {
            git([url: env.REPO_URL, branch: env.BRANCH])
            sh("make build-container")
            sh("make push-container")
            commitHash = sh(
                returnStdout: true,
                script: "git rev-parse --short HEAD").trim()
        }
    },
    mock_container: {
        node("util") {
            git([url: env.REPO_URL, branch: env.BRANCH])
            sh("make build-mock-container")
            sh("make push-mock-container")
        }
    }
    build(
        job: "ami_build-safe_vault_slave",
        parameters:
        [
            [
                $class: "StringParameterValue",
                name: "SAFE_COMMIT_HASH",
                value: commitHash
            ]
        ],
        wait: false)
}
