stage('build & push') {
    node('util') {
        git([url: env.REPO_URL, branch: env.BRANCH])
        sh('make build-container')
        sh('make push-container')
    }
    build(job: 'ami_build-safe_vault_slave', wait: false)
}
