stage("build") {
    node("util") {
        git([url: env.REPO_URL, branch: env.BRANCH])
        withCredentials(
            [[$class:
                "AmazonWebServicesCredentialsBinding",
                credentialsId: "packer",
                accessKeyVariable: "AWS_ACCESS_KEY_ID",
                secretKeyVariable: "AWS_SECRET_ACCESS_KEY"]]) {
            echo("Building Docker slave for ${env.SAFE_PROJECT} with ${env.SAFE_IMAGE_TAG} tag")
            sh("make box-rust_slave-windows-2016-x86_64-aws")
        }
    }
}
